enabled=1
back_video=/data/local/tmp/fake_video.mp4
front_video=/data/local/tmp/fake_video_front.mp4
noise_level=0
iso_min=100
iso_max=800
back_slot_a=/data/local/tmp/fake_video.slot_a.mp4
back_slot_b=/data/local/tmp/fake_video.slot_b.mp4
active_slot=A
qr_mode=1
back_rotate_180=0
front_rotate_180=1
front_mirror=1
chrome_front_rotate_180=0
chrome_front_mirror=0
preview_rotation=0
preview_mirror_h=0
preview_mirror_v=0
gyro_enabled=1
gyro_strength=0.1
front_user_set=1
sensor_orientation=90
pre_normalized=0
stream_camera=both
force_chrome_mode=0
auto_rotate_portrait=0
stream_postfx=1
